/**
 * Agent Inspector — web console.
 *
 * This file is the view layer only. Every judgement is produced by the
 * engine (src/engine/*): the console renders, filters and explains.
 *
 * Two product rules are enforced visually rather than in prose:
 *   - anything synthetic is labelled as a fixture at the point of use;
 *   - "not observed" is never rendered as "safe".
 */

import {
  inspectProject,
  inspectCommandText,
  createAuditLog,
  PlanOnlySandboxProvider,
  createSandboxProvider,
  policyPatchForFinding,
  APPROVAL_ACTIONS,
  FORBIDDEN_APPROVAL_ACTIONS,
  GITHUB_APP_PERMISSIONS,
  GITHUB_INSPECTION_WORKFLOW,
  GITHUB_LATER,
  parseRepoUrl,
  planRepositoryInspection,
  RULE_CATALOG,
  MCP_INSPECTION_PIPELINE,
  SANDBOX_LIMITATIONS,
  SANDBOX_MINIMUM_REQUIREMENTS,
  DISCOVERY_TARGETS_SPEC,
  GATEWAY_FLOW,
  EVENT,
  redactString,
  VERSION,
} from '../src/engine/index.js';

/* ================================================================== *
 * Embedded fixture — clearly synthetic, clearly labelled
 * ================================================================== */

const FIXTURE_LABEL = 'Embedded synthetic fixture (not a real repository)';

/**
 * Fixture sources come from fixtures/spec-demo via app/fixture-sources.json,
 * generated by scripts/build-web.mjs. They are never executed; they exist so
 * the console has something to inspect with no network and no local project.
 */
async function getFixtureSources() {
  if (Array.isArray(globalThis.__FIXTURE_SOURCES__) && globalThis.__FIXTURE_SOURCES__.length) {
    return globalThis.__FIXTURE_SOURCES__;
  }
  const res = await fetch('./fixture-sources.json');
  if (!res.ok) throw new Error('fixture-sources.json is missing — run: npm run build:web');
  const json = await res.json();
  return json.sources ?? [];
}
/* ================================================================== *
 * State + helpers
 * ================================================================== */

const state = {
  report: null,
  screen: 'dashboard',
  selectedAction: null,
  blastCategory: null,
  filter: '',
  onlyRisk: false,
  gateFilter: 'pending',
  decisions: {},        // actionId -> { decision, at }
  auditLog: null,
  auditVerdict: null,
  tamperedEvents: null,
  sourceLabel: null,
};

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function shortHash(h) {
  return h ? `${h.slice(0, 10)}…${h.slice(-6)}` : '—';
}

function statusClass(status) {
  return ['red', 'orange', 'yellow', 'green', 'grey'].includes(status) ? status : 'grey';
}

/* ================================================================== *
 * Inspection entry points
 * ================================================================== */

function setReport(report, sourceLabel) {
  state.report = report;
  state.sourceLabel = sourceLabel;
  state.selectedAction = report.actions[0]?.id ?? null;
  state.blastCategory = null;
  state.decisions = {};
  state.auditVerdict = null;
  state.tamperedEvents = null;

  // Rebuild the session ledger from the inspection's real ledger, then allow
  // approval events to be appended on top of the same chain.
  state.auditLog = createAuditLog({
    workspaceId: report.meta.workspaceId,
    agentId: report.meta.agentId,
  });
  state.auditLog.load(report.audit);

  renderAll();
  showScreen('dashboard');
}

function runCommandInspection(text) {
  const report = inspectCommandText(text, { workspace: 'session://pasted', agentId: 'autoclaw' });
  setReport(report, 'Pasted command (evaluated in this session)');
}

const SKIP_DIRS = ['node_modules', '.git', 'dist', 'build', '.next', 'coverage', 'vendor', '__pycache__'];
const SKIP_FILE = /(^|\/)(\.env(\.[a-z]+)?|id_(rsa|ed25519)|[^/]*\.(pem|key|p12|pfx))$/i;
const MAX_FILE = 512 * 1024;

async function filesToSources(fileList, opts = {}) {
  const sources = [];
  const skipped = [];
  for (const file of fileList) {
    const rel = (file.webkitRelativePath || file.name).replace(/^[^/]+\//, opts.stripRoot ? '' : '');
    const path = rel || file.name;
    if (SKIP_DIRS.some((d) => path.split('/').includes(d))) { skipped.push({ path, reason: 'excluded directory' }); continue; }
    if (SKIP_FILE.test(path)) { skipped.push({ path, reason: 'skipped by policy (secret-bearing file)' }); continue; }
    if (file.size > MAX_FILE) { skipped.push({ path, reason: 'larger than 512 KB' }); continue; }
    const content = await file.text();
    if (content.includes('\u0000')) { skipped.push({ path, reason: 'binary content' }); continue; }
    sources.push({ path, content });
  }
  return { sources, skipped };
}

async function inspectFiles(fileList, opts) {
  const { sources, skipped } = await filesToSources(fileList, opts);
  if (!sources.length) throw new Error('No readable text files were selected.');
  const report = inspectProject({ sources, options: { workspace: 'session://upload', agentId: 'autoclaw' } });
  report.meta.skipped = skipped;
  setReport(report, `Uploaded files (${sources.length} read, ${skipped.length} skipped)`);
}

/* ================================================================== *
 * Rendering — shell
 * ================================================================== */

function renderAll() {
  const report = state.report;
  $('#version').textContent = `v${VERSION}`;

  if (!report) {
    $('#count-trace').textContent = '';
    $('#count-blast').textContent = '';
    $('#count-rep').textContent = '';
    $('#count-gate').textContent = '';
    $('#audit-pill').textContent = 'audit: —';
    renderDashboard();
    renderTrace();
    renderBlast();
    renderRepercussions();
    renderGate();
    return;
  }

  $('#count-trace').textContent = report.actions.length;
  $('#count-blast').textContent = report.graphs.blastRadius.stats.categoriesObserved;
  $('#count-rep').textContent = report.repercussions.cards.length;
  const pending = pendingDecisions().length;
  $('#count-gate').textContent = pending;

  $('#policy-pill').textContent = `policy: ${report.policy.id}`;
  const auditOk = currentAuditVerification().valid;
  $('#audit-pill').textContent = `audit: ${auditOk ? 'chain intact' : 'CHAIN BROKEN'} (${auditEvents().length})`;
  $('#audit-pill').className = `pill ${auditOk ? 'pill-ok' : 'pill-bad'}`;

  renderDashboard();
  renderTrace();
  renderBlast();
  renderRepercussions();
  renderGate();
}

function showScreen(name) {
  const target = document.getElementById(`screen-${name}`);
  if (!target) return;
  state.screen = name;
  $$('.screen').forEach((s) => s.classList.toggle('is-active', s.id === `screen-${name}`));
  $$('.screen-tab').forEach((t) => {
    const active = t.dataset.screen === name;
    t.classList.toggle('is-active', active);
    t.setAttribute('aria-selected', String(active));
  });
  if (typeof window.scrollTo === 'function') window.scrollTo({ top: 0, behavior: 'smooth' });
}

/* ================================================================== *
 * Screen 1 — Dashboard
 * ================================================================== */

function renderDashboard() {
  const target = $('#dashboard-result');
  const report = state.report;
  if (!report) {
    target.innerHTML = `
      <div class="card">
        <h3>How this works</h3>
        <p class="note">
          Choose an input above and press <strong>INSPECT</strong>. The engine parses shell scripts, package
          manifests, container definitions, CI workflows, agent configs, MCP configs and program source, then
          applies deterministic rules R001–R014 and produces a hash-chained audit ledger.
        </p>
        <div class="kv">
          <dt>Rules</dt><dd>${esc(RULE_CATALOG.map((r) => r.id).join(' '))}</dd>
          <dt>Discovery targets</dt><dd>${esc(DISCOVERY_TARGETS_SPEC.join(' · '))}</dd>
          <dt>Decision set</dt><dd>ALLOW · ALLOW_WITH_LOG · REQUIRE_APPROVAL · SANDBOX_ONLY · DENY</dd>
          <dt>Fail-closed rule</dt><dd>unknown ⇒ never ALLOW</dd>
        </div>
      </div>`;
    return;
  }

  const o = report.risk.overall;
  const dims = report.risk.dimensions;
  const order = ['filesystem_risk', 'execution_risk', 'network_risk', 'credential_risk', 'agentic_risk', 'supply_chain_risk', 'persistence_risk', 'identity_risk'];

  const dimCards = order.map((key) => {
    const d = dims[key];
    const cls = statusClass(d.status);
    const scoreText = d.state === 'not-inspected' ? 'NOT OBSERVED' : `${d.score}/5 · ${d.scoreLabel}`;
    const why = d.evidence.slice(0, 4).map((e) => `<li>${esc(e.rule ?? '—')} ${esc(String(e.action ?? '').slice(0, 110))}</li>`).join('');
    const unknown = d.unknown.slice(0, 3).map((u) => `<p class="dim-unknown">unknown · ${esc(u)}</p>`).join('');
    return `
      <div class="dim">
        <div class="dim-head">
          <span class="dim-name">${esc(d.label)}</span>
          <span class="dim-score ${cls}">${esc(scoreText)}</span>
        </div>
        <div class="bar"><span class="${cls}" style="width:${(d.score / 5) * 100}%"></span></div>
        <ul class="dim-why">${why || '<li>No evidence of this kind of activity in the inspected set.</li>'}</ul>
        ${unknown}
      </div>`;
  }).join('');

  const notFound = report.discovery.notFound.map((n) => `<li>${esc(n.note)}</li>`).join('');
  const uninspected = report.uninspected.slice(0, 8).map((u) => `<li>${esc(u.reason)}</li>`).join('');

  target.innerHTML = `
    <div class="banner ${statusClass(o.status)}">
      <div>
        <div class="banner-word">${esc(o.exposureWord)}</div>
        <div class="banner-meta">confidence ${esc(report.risk.confidence)}% · ${esc(report.stats.actionsDetected)} actions detected · ${esc(report.stats.findings)} findings</div>
      </div>
      <div class="banner-meta">
        <span class="banner-tag">${esc(report.meta.mode)}</span>
        <span class="banner-tag">${esc(state.sourceLabel ?? report.meta.kind)}</span>
        <span class="banner-tag">${esc(report.meta.agentId)}</span>
      </div>
    </div>

    <div class="card">
      <h3>Exposure by dimension</h3>
      <div class="dim-grid">${dimCards}</div>
      <p class="note" style="margin-top:12px">A dimension marked NOT OBSERVED had no evidence in the inspected set. That is an absence of evidence, not evidence of safety.</p>
    </div>

    <div class="card">
      <h3>What the engine did</h3>
      <div class="stats">
        <div class="stat"><div class="stat-num">${esc(report.stats.actionsDetected)}</div><div class="stat-lbl">actions</div></div>
        <div class="stat"><div class="stat-num">${esc(report.stats.actionsAllowed)}</div><div class="stat-lbl">allow</div></div>
        <div class="stat"><div class="stat-num">${esc(report.stats.actionsRequiringApproval)}</div><div class="stat-lbl">approval</div></div>
        <div class="stat"><div class="stat-num">${esc(report.stats.actionsDenied)}</div><div class="stat-lbl">deny</div></div>
        <div class="stat"><div class="stat-num">${esc(report.meta.sourceCount)}</div><div class="stat-lbl">files read</div></div>
        <div class="stat"><div class="stat-num">${esc(report.stats.coverage)}%</div><div class="stat-lbl">coverage</div></div>
      </div>
      <p class="note" style="margin-top:10px">${esc(report.meta.executionDisclaimer)}</p>
    </div>

    ${(notFound || uninspected) ? `
    <div class="card">
      <h3>Absences and unknowns</h3>
      <ul class="dim-why">${notFound}${uninspected}</ul>
      <p class="note">These are stated explicitly so a missing artifact is never silently read as "clean".</p>
    </div>` : ''}

    ${report.mcp.servers.length ? `
    <div class="card">
      <h3>MCP inspection pipeline</h3>
      <p class="note">${esc(report.mcp.pipeline.join(' → '))}</p>
      <p class="note">${esc(report.mcp.servers.length)} server(s) parsed statically. None were started. Snyk's Agent Scan documentation warns that scanning an MCP config executes the configured stdio commands; this inspector refuses to do that at inspection time.</p>
    </div>` : ''}
  `;
}

/* ================================================================== *
 * Screen 2 — Action trace
 * ================================================================== */

function actionById(id) {
  return state.report?.actions.find((a) => a.id === id) ?? null;
}

function traceRows() {
  const g = state.report.graphs.actionGraph;
  const nodes = g.nodes;
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const children = new Map();
  for (const e of g.edges) {
    if (e.kind === 'sequence') continue;
    if (!children.has(e.from)) children.set(e.from, []);
    children.get(e.from).push(e);
  }
  const depth = new Map();
  const walk = (id, d) => {
    if (depth.has(id) && depth.get(id) <= d) return;
    depth.set(id, d);
    for (const e of children.get(id) ?? []) walk(e.to, d + 1);
  };
  for (const r of g.roots) walk(r, 0);
  for (const n of nodes) if (!depth.has(n.id)) depth.set(n.id, 0);

  return nodes
    .map((n) => ({ node: n, depth: depth.get(n.id) ?? 0, edgeKinds: g.edges.filter((e) => e.to === n.id).map((e) => e.kind) }))
    .sort((a, b) => (a.depth - b.depth) || ((a.node.file ?? '').localeCompare(b.node.file ?? '')) || ((a.node.line ?? 0) - (b.node.line ?? 0)));
}

function renderTrace() {
  const tree = $('#trace-tree');
  const detail = $('#trace-detail');
  if (!tree) return;

  if (!state.report) {
    tree.innerHTML = '<li class="empty">Run an inspection first.</li>';
    detail.innerHTML = '<p class="empty">Select an action to see its evidence.</p>';
    return;
  }

  const filter = state.filter.toLowerCase();
  const rows = traceRows().filter(({ node }) => {
    if (state.onlyRisk && node.severity === 0) return false;
    if (!filter) return true;
    return `${node.label} ${node.file ?? ''} ${node.rules.join(' ')} ${node.capabilities.join(' ')}`.toLowerCase().includes(filter);
  });

  tree.innerHTML = rows.map(({ node, depth, edgeKinds }) => {
    const cls = statusClass(node.status);
    const kindChip = node.origin === 'code'
      ? '<span class="chip code">code</span>'
      : edgeKinds.includes('downstream') ? '<span class="chip downstream">downstream</span>' : '';
    const evChip = node.evidenceType === 'observed'
      ? '<span class="chip observed">observed</span>'
      : node.evidenceType === 'inferred' ? '<span class="chip inferred">inferred</span>' : '<span class="chip unknown">unknown</span>';
    return `
      <li style="margin-left:${depth * 16}px">
        <button class="node ${state.selectedAction === node.id ? 'is-active' : ''}" data-action="${esc(node.id)}">
          <span class="dot ${cls}" title="${esc(node.severityLabel)}"></span>
          <span class="node-code">${esc(node.label)}</span>
          ${kindChip}${evChip}
          <span style="flex:1"></span>
          <span class="node-file">${esc(node.file ?? '—')}${node.line ? `:${node.line}` : ''}</span>
        </button>
      </li>`;
  }).join('') || '<li class="empty">No actions match the filter.</li>';

  $$('.node', tree).forEach((btn) => {
    btn.addEventListener('click', () => {
      state.selectedAction = btn.dataset.action;
      renderTrace();
    });
  });

  renderTraceDetail();
}

function renderTraceDetail() {
  const detail = $('#trace-detail');
  const node = state.report?.graphs.actionGraph.nodes.find((n) => n.id === state.selectedAction);
  if (!node) {
    detail.innerHTML = '<p class="empty">Select an action to see its evidence.</p>';
    return;
  }

  const findings = state.report.findings.filter((f) => f.actionId === node.id);
  const caps = state.report.capabilities.filter((c) => c.actionId === node.id);
  const decision = state.report.decisions.find((d) => d.actionId === node.id);

  const evidence = findings.flatMap((f) => f.evidence.map((e) => `[${f.rule}] ${e}`));
  const isDestructive = node.rules.includes('R001');
  const top = findings.slice().sort((a, b) => b.severity - a.severity)[0];

  detail.innerHTML = `
    <div class="detail-head">
      <div>
        <p class="detail-title">${esc(node.command || node.actionType)}</p>
        <p class="note">${esc(node.actionType)} · origin ${esc(node.origin)} · ${esc(node.language)}</p>
      </div>
      <span class="sev ${statusClass(node.status)}">${esc(node.severityLabel)}</span>
    </div>

    <dl class="kv">
      <dt>Action</dt><dd>${esc(node.label)}</dd>
      <dt>Type</dt><dd>${esc(node.actionType)}</dd>
      <dt>Scope</dt><dd>${esc(top?.scope ?? 'not classified')}</dd>
      <dt>Destructive</dt><dd>${isDestructive ? 'YES' : 'no'}</dd>
      <dt>Observed target</dt><dd>${esc(findings.flatMap((f) => f.location.file ? [`${f.location.file}${f.location.line ? `:${f.location.line}` : ''}`] : []).join(', ') || node.file || '—')}</dd>
      <dt>Evidence</dt><dd><span class="chip ${esc(node.evidenceType)}">${esc(node.evidenceType)}</span> · ${esc(top?.confidence ?? 'n/a')}</dd>
      <dt>Capabilities</dt><dd>${esc(node.capabilities.join(', ') || 'none recorded')}</dd>
      <dt>Decision</dt><dd>${esc(decision?.decision ?? 'n/a')}</dd>
      ${node.downstreamFiles ? `<dt>Reaches</dt><dd>${esc(node.downstreamFiles.slice(0, 12).join(', '))}</dd>` : ''}
    </dl>

    <div class="evidence">
      <strong>Recommendation</strong>
      <ul>${(top?.recommendedControl ? [top.recommendedControl] : ['No control required; nothing was flagged for this action.']).map((r) => `<li>${esc(r)}</li>`).join('')}</ul>
      ${evidence.length ? `<strong>Evidence (${evidence.length})</strong><ul>${evidence.slice(0, 14).map((e) => `<li>${esc(e)}</li>`).join('')}</ul>` : ''}
      ${caps.length ? `<strong>Capability records</strong><ul>${caps.map((c) => `<li>${esc(c.capabilityType)} → ${esc(c.target ?? 'unknown')} <span class="chip">${esc(c.scope)}</span></li>`).join('')}</ul>` : ''}
    </div>

    ${top ? `
    <div class="block">
      <h4>Why is this elevated?</h4>
      <ul>${(top.why ?? []).map((w) => `<li>${esc(w)}</li>`).join('')}</ul>
    </div>
    <div class="block">
      <h4>What if this is malicious?</h4>
      <ul>
        <li>Project files could be modified.</li>
        <li>Network requests could be made.</li>
        <li>Environment variables could be accessed.</li>
        <li>Child processes could be launched.</li>
      </ul>
      <p class="note">Current evidence does <strong>not</strong> establish that this project is malicious. The concern is the capability available to it.</p>
    </div>` : ''}
  `;
}

/* ================================================================== *
 * Screen 3 — Blast radius (SVG)
 * ================================================================== */

function renderBlast() {
  const wrap = $('#blast-graph');
  if (!wrap) return;
  if (!state.report) {
    wrap.innerHTML = '<p class="empty">Run an inspection first.</p>';
    $('#blast-detail').innerHTML = '<p class="empty">Select a category to see the resources behind it.</p>';
    return;
  }

  const blast = state.report.graphs.blastRadius;
  const cats = blast.categories;
  const W = 900;
  const top = 70;
  const rowH = 120;
  const perRow = 5;
  const boxW = 156;
  const boxH = 74;
  const gapX = (W - 40 - perRow * boxW) / (perRow - 1);

  const fill = {
    red: '#fdecea', orange: '#fdf0e3', yellow: '#fdf6e0', green: '#e8f6ee', grey: '#f1f2f5',
  };
  const stroke = {
    red: '#e8b4b0', orange: '#eecba7', yellow: '#e6d391', green: '#b7ddc8', grey: '#d8dbe2',
  };
  const textColor = {
    red: '#8f1f19', orange: '#8f4513', yellow: '#6f5700', green: '#135f3b', grey: '#5b6472',
  };

  let svg = `<svg viewBox="0 0 ${W} 400" role="img" aria-label="Blast radius graph: the agent and the capability categories it can affect.">`;
  svg += `<text x="${W / 2}" y="20" text-anchor="middle" font-size="13" fill="#6b7280">blast radius · observed capability surface</text>`;

  // Agent node
  svg += `<g class="gnode"><rect x="${W / 2 - 92}" y="30" width="184" height="42" rx="9" fill="#16191d"/>`;
  svg += `<text x="${W / 2}" y="56" text-anchor="middle" font-size="14" font-weight="700" fill="#ffffff">AGENT</text></g>`;

  cats.forEach((cat, i) => {
    const row = Math.floor(i / perRow);
    const col = i % perRow;
    const x = 20 + col * (boxW + gapX);
    const y = top + row * rowH;
    const s = statusClass(cat.status);
    svg += `<path d="M ${W / 2} 72 C ${W / 2} ${y - 10}, ${x + boxW / 2} ${72}, ${x + boxW / 2} ${y}" fill="none" stroke="${stroke[s]}" stroke-width="${cat.count ? Math.min(4, 1 + Math.log2(cat.count + 1)) : 1}" ${cat.count ? '' : 'stroke-dasharray="4 4"'}/>`;
    svg += `<g class="gnode" data-cat="${esc(cat.category)}" tabindex="0" role="button" aria-label="${esc(cat.category)}: ${esc(cat.scoreLabel)}">
      <rect x="${x}" y="${y}" width="${boxW}" height="${boxH}" rx="9" fill="${fill[s]}" stroke="${stroke[s]}"/>
      <text x="${x + 12}" y="${y + 22}" font-size="11.5" font-weight="700" fill="${textColor[s]}">${esc(cat.category)}</text>
      <text x="${x + 12}" y="${y + 41}" font-size="11" fill="#5b6472">${esc(cat.scoreLabel)}</text>
      <text x="${x + 12}" y="${y + 60}" font-size="10.5" fill="#6b7280">${cat.count ? `${cat.count} node(s)` : 'not observed'}</text>
    </g>`;
  });
  svg += '</svg>';
  wrap.innerHTML = svg;

  $('#blast-legend').innerHTML = [
    ['green', 'allowed / low exposure'], ['yellow', 'controlled exposure'],
    ['orange', 'elevated exposure'], ['red', 'blocked / dangerous'], ['grey', 'unknown / not observed'],
  ].map(([c, label]) => `<span><i class="lg-dot" style="background:${fill[c]};border:1px solid ${stroke[c]}"></i>${esc(label)}</span>`).join('');

  $('#blast-note').textContent = blast.absentNote;

  $$('.gnode[data-cat]', wrap).forEach((g) => {
    const open = () => { state.blastCategory = g.dataset.cat; renderBlastDetail(); };
    g.addEventListener('click', open);
    g.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); } });
  });

  if (state.blastCategory) renderBlastDetail();
}

function renderBlastDetail() {
  const detail = $('#blast-detail');
  const cat = state.report.graphs.blastRadius.categories.find((c) => c.category === state.blastCategory);
  if (!cat) {
    detail.innerHTML = '<p class="empty">Select a category to see the resources behind it.</p>';
    return;
  }
  const items = cat.items.length ? cat.items.map((it) => `
    <div class="rep-cell" style="border-top:1px solid var(--line);padding-top:10px;margin-top:10px">
      <h5>${esc(it.capability)} <span class="sev ${statusClass(it.status)}">${esc(it.severityLabel)}</span></h5>
      <p><strong>target</strong> ${esc(it.target)}</p>
      <p><strong>scope</strong> ${esc(it.scope)} ${it.rule ? `· <strong>rule</strong> ${esc(it.rule)}` : ''}</p>
      <p class="note">${esc(it.evidence ?? '')}</p>
      <p class="note">${esc(it.file ?? '—')}${it.line ? `:${it.line}` : ''}</p>
    </div>`).join('') : '<p class="empty">No capability of this kind was observed. That is not the same as safe.</p>';

  detail.innerHTML = `
    <h3>${esc(cat.category)} — ${esc(cat.scoreLabel)}</h3>
    <p class="note">${cat.count} capability record(s). ${esc(cat.untested ? 'Not observed in the inspected set.' : 'Observed directly in the inspected files.')}</p>
    ${items}
  `;
}

/* ================================================================== *
 * Screen 4 — Repercussions
 * ================================================================== */

function renderRepercussions() {
  const list = $('#rep-list');
  const unknowns = $('#rep-unknowns');
  if (!list) return;

  if (!state.report) {
    list.innerHTML = '<div class="card"><p class="empty">Run an inspection first.</p></div>';
    unknowns.innerHTML = '';
    return;
  }

  const { cards, projectUnknowns, summary } = state.report.repercussions;

  list.innerHTML = cards.map((c) => `
    <article class="rep ${statusClass(c.status)}" id="${esc(c.id)}">
      <div class="rep-head">
        <h3 class="rep-title">${esc(c.title)}</h3>
        <span class="sev ${statusClass(c.status)}">${esc(c.severityLabel)}</span>
        <span class="chip">${esc(c.rule)}</span>
        <span class="chip">${esc(c.capabilityLabel ?? c.capability ?? '—')}</span>
      </div>
      <div class="rep-grid">
        <div class="rep-cell">
          <h5>Observed action</h5>
          <p>${esc(c.observedAction)}</p>
          <h5 style="margin-top:8px">Observed scope</h5>
          <p>${esc(c.observedScope)}</p>
        </div>
        <div class="rep-cell">
          <h5>Potential consequence</h5>
          <p>${esc(c.potentialConsequence)}</p>
        </div>
        <div class="rep-cell">
          <h5>Unknowns</h5>
          <ul>${c.unknowns.map((u) => `<li>${esc(u)}</li>`).join('')}</ul>
        </div>
        <div class="rep-cell">
          <h5>Recommended control</h5>
          <p>${esc(c.recommendedControl)}</p>
        </div>
      </div>
      <div class="row-btns">
        <button class="btn btn-ghost" data-why="${esc(c.id)}">WHY?</button>
        <button class="btn btn-ghost" data-whatif="${esc(c.id)}">WHAT IF?</button>
        <button class="btn btn-ghost" data-safe="${esc(c.findingId)}">MAKE IT SAFE</button>
        <span class="note" style="align-self:center">decision: <strong>${esc(c.decision)}</strong></span>
      </div>
      <div class="block" data-out="${esc(c.id)}" hidden></div>
    </article>`).join('') || '<div class="card"><p class="empty">No findings above the reporting threshold.</p></div>';

  $$('[data-why]', list).forEach((btn) => btn.addEventListener('click', () => {
    const card = cards.find((c) => c.id === btn.dataset.why);
    toggleBlock(btn.dataset.why, `
      <h4>Why this matters</h4>
      <p>${esc(card.whyItMatters)}</p>
      <h4 style="margin-top:10px">Capability vs intent</h4>
      <p>Findings describe what is possible, never what is intended. ${esc(card.potentialConsequence)}</p>
    `);
  }));

  $$('[data-whatif]', list).forEach((btn) => btn.addEventListener('click', () => {
    const card = cards.find((c) => c.id === btn.dataset.whatif);
    toggleBlock(btn.dataset.whatif, `
      <h4>What if this is malicious?</h4>
      <ul>${card.whatIf.map((w) => `<li>${esc(w)}</li>`).join('')}</ul>
      <p class="note">Current evidence does <strong>not</strong> establish that this is malicious. The concern is the capability available.</p>
    `);
  }));

  $$('[data-safe]', list).forEach((btn) => btn.addEventListener('click', () => {
    const finding = state.report.findings.find((f) => f.id === btn.dataset.safe);
    const patch = policyPatchForFinding(finding);
    toggleBlock(`rep_${finding.id}`, `
      <h4>Proposed policy patch</h4>
      <pre class="yaml">${esc(patch.yaml)}</pre>
      <div class="row-btns">
        <button class="btn" data-apply="${esc(finding.id)}">Propose this policy change (requires human approval)</button>
      </div>
      <p class="note" style="margin-top:8px">
        Applying a policy change is a two-step action: proposing it records a POLICY_CHANGED event in the session
        ledger, and activating it requires explicit confirmation. The Inspector never edits a policy file on its own.
      </p>
    `);
    const applyBtn = $(`[data-apply="${finding.id}"]`);
    applyBtn?.addEventListener('click', () => {
      const confirmed = window.confirm(
        'Record this policy change proposal in the audit ledger?\n\n'
        + 'This does not enable the change. It records the intent, with reasons, as a tamper-evident event.',
      );
      if (!confirmed) return;
      state.auditLog.append(EVENT.POLICY_CHANGED, {
        capability: finding.capability,
        rule: finding.rule,
        proposed_patch: patch.object,
        status: 'proposed',
        requires_human_activation: true,
      });
      state.auditVerdict = null;
      renderAll();
    });
  }));

  unknowns.innerHTML = `
    <h3>Project-level unknowns</h3>
    <ul class="dim-why">${(projectUnknowns.length ? projectUnknowns : ['None identified.']).map((u) => `<li>${esc(u)}</li>`).join('')}</ul>
    <h3 style="margin-top:12px">Summary</h3>
    <p class="note">${esc(summary.total)} findings above threshold — ${esc(summary.critical)} critical, ${esc(summary.elevated)} elevated, ${esc(summary.moderate)} moderate, ${esc(summary.low)} low.</p>
  `;
}

function toggleBlock(id, html) {
  const box = $(`[data-out="${id}"]`);
  if (!box) return;
  const open = !box.hidden && box.innerHTML === html;
  box.innerHTML = html;
  box.hidden = open;
}

/* ================================================================== *
 * Screen 5 — Approval gate
 * ================================================================== */

function auditEvents() {
  return state.auditLog ? state.auditLog.events() : [];
}

function currentAuditVerification() {
  if (!state.auditLog) return { valid: true, reason: 'no ledger', brokenAt: null };
  return state.auditLog.verify();
}

function pendingDecisions() {
  if (!state.report) return [];
  return state.report.decisions.filter((d) => ['REQUIRE_APPROVAL', 'SANDBOX_ONLY', 'DENY'].includes(d.decision));
}

function renderGate() {
  const list = $('#gate-list');
  const table = $('#audit-table');
  const verdict = $('#audit-verdict');
  if (!list) return;

  if (!state.report) {
    list.innerHTML = '<p class="empty">Run an inspection first.</p>';
    table.innerHTML = '';
    verdict.textContent = '';
    return;
  }

  const items = pendingDecisions();
  list.innerHTML = items.length ? items.map((d) => {
    const handled = state.decisions[d.actionId];
    const cls = d.decision === 'DENY' ? 'deny' : d.decision === 'SANDBOX_ONLY' ? 'req' : 'req';
    const caps = (d.capabilities ?? []).map((c) => `<span class="chip">${esc(c)}</span>`).join('') || '<span class="chip">none recorded</span>';
    const unique = new Set((d.capabilities ?? []).map((c) => c.split('.')[0]));
    return `
      <div class="gate-item" id="gate-${esc(d.actionId)}">
        <h4>${esc(d.request.command)} ${esc((d.request.arguments ?? []).join(' '))}</h4>
        <p class="note">agent ${esc(d.request.agent_id)} · ${esc(d.request.action_type)} · ${esc(d.request.working_directory)}</p>
        <div class="gate-caps">${caps}</div>
        <div class="verdict-line ${cls}">policy result: ${esc(d.decision)}${d.approvalId ? ` · ${esc(d.approvalId)}` : ''}</div>
        <ul class="reasons">${d.reasons.slice(0, 4).map((r) => `<li>${esc(r)}</li>`).join('')}</ul>
        ${handled
          ? `<p class="note" style="margin-top:10px">Handled: <strong>${esc(handled.label)}</strong> at ${esc(handled.at)}</p>`
          : `<div class="row-btns">
              ${APPROVAL_ACTIONS.map((a) => `<button class="btn ${a.id === 'deny' ? 'btn-danger' : a.id.startsWith('allow') ? 'btn-ok' : 'btn-ghost'}"
                 data-approve="${esc(a.id)}" data-action-id="${esc(d.actionId)}"
                 title="${esc(a.effect)}">${esc(a.label)}</button>`).join('')}
             </div>
             <p class="note" style="margin-top:8px">There is deliberately no "allow everything" option. The blocked variants are: ${esc(FORBIDDEN_APPROVAL_ACTIONS.join(', '))}</p>`}
      </div>`;
  }).join('') : '<p class="empty">Nothing is waiting for approval.</p>';

  $$('[data-approve]', list).forEach((btn) => btn.addEventListener('click', () => handleApproval(btn.dataset.actionId, btn.dataset.approve)));

  /* audit table */
  const events = auditEvents();
  table.innerHTML = `
    <thead><tr><th>seq</th><th>type</th><th>timestamp</th><th>hash</th><th>previous</th></tr></thead>
    <tbody>${events.map((e) => `
      <tr class="${state.auditVerdict && state.auditVerdict.brokenAt === e.seq ? 'bad' : ''}">
        <td>${esc(e.seq)}</td><td>${esc(e.type)}</td><td>${esc(e.timestamp)}</td>
        <td class="hash">${esc(shortHash(e.hash))}</td><td class="hash">${esc(shortHash(e.previous_hash))}</td>
      </tr>`).join('')}</tbody>`;

  if (state.tamperedEvents) {
    const v = state.auditVerdict;
    verdict.className = 'verdict bad';
    verdict.textContent = `simulated tamper detected at event ${v.brokenAt}: ${v.reason}`;
  } else if (state.auditVerdict) {
    verdict.className = `verdict ${state.auditVerdict.valid ? 'ok' : 'bad'}`;
    verdict.textContent = state.auditVerdict.valid
      ? `chain intact · ${events.length} events · head ${shortHash(state.auditLog.head())}`
      : `chain broken at ${state.auditVerdict.brokenAt}: ${state.auditVerdict.reason}`;
  } else {
    verdict.className = 'verdict';
    verdict.textContent = `${events.length} events recorded. Verify to recompute the chain.`;
  }
}

function handleApproval(actionId, approvalId) {
  const action = APPROVAL_ACTIONS.find((a) => a.id === approvalId);
  const decision = state.report.decisions.find((d) => d.actionId === actionId);
  if (!action || !decision) return;

  if (action.id === 'inspect-deeper') {
    const node = state.report.graphs.actionGraph.nodes.find((n) => n.id === actionId);
    const reached = node?.downstreamFiles ?? [];
    window.alert(reached.length
      ? `Already inspected downstream: ${reached.join(', ')}\n\nRe-analysis uses the same deterministic rules, so no new conclusions appear without new files.`
      : 'No downstream files were reachable from this action in the inspected set. That is an unknown, not a clean result.');
    return;
  }

  if (action.id === 'deny') {
    state.auditLog.append(EVENT.ACTION_DENIED, {
      action: decision.request.command, arguments: decision.request.arguments,
      decision: 'DENY', operator: 'user', result: 'denied', policy: decision.policyId,
    });
  } else if (action.decision === 'SANDBOX_ONLY') {
    state.auditLog.append(EVENT.ACTION_APPROVED, {
      action: decision.request.command, arguments: decision.request.arguments,
      decision: 'SANDBOX_ONLY', operator: 'user', result: 'approved-in-sandbox',
      execution_environment: 'sandbox', policy: decision.policyId,
    });
    state.auditLog.append(EVENT.SANDBOX_STARTED, { provider: 'docker (hardened)', network: 'none', note: 'plan recorded; no provider is configured in this session, so nothing executed' });
  } else {
    state.auditLog.append(EVENT.ACTION_APPROVED, {
      action: decision.request.command, arguments: decision.request.arguments,
      decision: action.id === 'allow-once' ? 'ALLOW' : 'ALLOW_WITH_LOG',
      scope: action.id === 'allow-project' ? 'project' : 'once',
      operator: 'user', result: 'approved', policy: decision.policyId,
    });
  }

  state.decisions[actionId] = {
    label: action.label,
    at: new Date().toISOString(),
  };
  state.auditVerdict = null;
  renderAll();
}

/* ================================================================== *
 * Input wiring
 * ================================================================== */

function wireInputs() {
  $$('.itab').forEach((tab) => tab.addEventListener('click', () => {
    $$('.itab').forEach((t) => t.classList.toggle('is-active', t === tab));
    $$('.input-pane').forEach((p) => p.classList.toggle('is-active', p.id === `pane-${tab.dataset.input}`));
  }));

  $$('.screen-tab').forEach((tab) => tab.addEventListener('click', () => showScreen(tab.dataset.screen)));

  const error = $('#input-error');
  const fail = (msg) => { error.textContent = msg; error.hidden = false; };
  const clearError = () => { error.hidden = true; };

  $('#inspect-btn').addEventListener('click', async () => {
    clearError();
    const active = $('.itab.is-active')?.dataset.input;
    try {
      if (active === 'paste') {
        const text = $('#cmd-input').value.trim();
        if (!text) return fail('Enter a command first.');
        runCommandInspection(text);
      } else if (active === 'script') {
        const files = $('#file-input').files;
        if (!files?.length) return fail('Select one or more files.');
        await inspectFiles(files, { stripRoot: false });
      } else if (active === 'project') {
        const files = $('#dir-input').files;
        if (!files?.length) return fail('Select a project directory.');
        await inspectFiles(files, { stripRoot: true });
      } else if (active === 'json') {
        const file = $('#json-input').files?.[0];
        if (!file) return fail('Select an inspection JSON file.');
        const parsed = JSON.parse(await file.text());
        setReport(parsed, `Loaded report: ${file.name}`);
      } else if (active === 'fixture') {
        await loadFixture();
      } else if (active === 'github') {
        return fail('Repository fetching runs through the CLI for safety. Copy the command shown in the plan above.');
      }
    } catch (err) {
      fail(String(err?.message ?? err));
    }
  });

  $('#sandbox-btn').disabled = false;
  $('#sandbox-btn').addEventListener('click', async () => {
    const provider = createSandboxProvider({ provider: 'plan' });
    const { handle } = await provider.create({ workspace: '<workspace>', image: 'node:22-alpine' });
    const result = await provider.execute(handle, 'node bin/contentpulse.js run --config sources.yaml');
    window.alert(
      'Sandbox plan (nothing executed)\n\n'
      + `docker ${(result.container ?? []).join(' ')}\n\n`
      + 'Why nothing ran:\n'
      + '• the default provider refuses execution (fail closed);\n'
      + `• ${SANDBOX_LIMITATIONS[0]}\n\n`
      + 'Minimum required controls:\n'
      + SANDBOX_MINIMUM_REQUIREMENTS.map((r) => `• ${r.label}`).join('\n'),
    );
  });

  $('#load-fixture').addEventListener('click', () => {
    clearError();
    loadFixture().catch((err) => fail(String(err?.message ?? err)));
  });
  $('#load-real').addEventListener('click', () => {
    clearError();
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json,application/json';
    input.addEventListener('change', async () => {
      const file = input.files?.[0];
      if (!file) return;
      try {
        setReport(JSON.parse(await file.text()), `Local report: ${file.name}`);
      } catch (err) { fail(`Could not read report: ${err.message}`); }
    });
    input.click();
  });

  $('#gh-input').addEventListener('input', (e) => {
    const plan = planRepositoryInspection(e.target.value);
    const box = $('#gh-plan');
    if (!plan.ok) { box.innerHTML = ''; return; }
    box.innerHTML = `
      <div class="kv">
        <dt>Permissions</dt><dd>${esc(Object.entries(GITHUB_APP_PERMISSIONS).map(([k, v]) => `${k}:${v}`).join(', '))}</dd>
        <dt>Steps</dt><dd>${esc(GITHUB_INSPECTION_WORKFLOW.join(' → '))}</dd>
        <dt>Later</dt><dd>${esc(GITHUB_LATER.join(' · '))}</dd>
        <dt>Run</dt><dd>npm run inspect -- --github ${esc(plan.repo.owner)}/${esc(plan.repo.repo)} --format json --out report.json</dd>
      </div>
      <p class="note" style="margin-top:8px">${esc(plan.guardrails[0])} ${esc(plan.guardrails[1])}</p>`;
  });

  $('#trace-filter').addEventListener('input', (e) => { state.filter = e.target.value; renderTrace(); });
  $('#trace-only-risk').addEventListener('change', (e) => { state.onlyRisk = e.target.checked; renderTrace(); });

  $('#audit-verify').addEventListener('click', () => {
    state.tamperedEvents = null;
    state.auditVerdict = state.auditLog.verify();
    renderGate();
  });

  $('#audit-tamper').addEventListener('click', () => {
    // Educational demonstration on an in-memory copy. The real ledger is not
    // modified: this exists so the tamper-evidence claim is checkable.
    const copy = state.auditLog.events().map((e) => JSON.parse(JSON.stringify(e)));
    if (copy.length < 2) {
      window.alert('Not enough events to demonstrate tampering. Record a decision first.');
      return;
    }
    const target = copy[Math.max(0, copy.length - 2)];
    target.payload = { ...target.payload, tampered: 'an attacker edited this event after the fact' };
    const testLog = createAuditLog({ workspaceId: 'tamper-demo', agentId: 'autoclaw' });
    testLog.load({ events: copy });
    state.tamperedEvents = target.seq;
    state.auditVerdict = testLog.verify();
    renderGate();
  });
}

function loadFixture() {
  return getFixtureSources().then((sources) => {
    if (!sources.length) throw new Error('The fixture is empty. Run: npm run build:web');
    const report = inspectProject({
      sources,
      options: { workspace: 'fixture://contentpulse-demo', agentId: 'autoclaw' },
    });
    report.meta.fixture = FIXTURE_LABEL;
    setReport(report, FIXTURE_LABEL);
  });
}

/* ================================================================== *
 * Boot
 * ================================================================== */

async function boot() {
  wireInputs();
  $('#footer-note').textContent = `${GATEWAY_FLOW.length}-stage gateway · adapters: openclaw, autoclaw, codex, claude-code, cursor, mcp, generic · nothing executed · secrets redacted at the engine boundary`;
  renderAll();

  // Deep links, also used to render a specific state for screenshots:
  //   ?load=fixture            load the synthetic fixture
  //   ?load=report             load dist/fixture-report.json
  //   ?screen=trace|blast|repercussions|gate
  const params = new URLSearchParams(globalThis.location?.search ?? '');
  const load = params.get('load');
  const error = $('#input-error');

  try {
    if (load === 'fixture') {
      await loadFixture();
    } else if (load === 'report') {
      const res = await fetch('./fixture-report.json');
      if (res.ok) setReport(await res.json(), 'dist/fixture-report.json');
    }
  } catch (err) {
    error.textContent = String(err?.message ?? err);
    error.hidden = false;
  }

  const screen = params.get('screen');
  if (screen) showScreen(screen);
  renderAll();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => { boot(); });
} else {
  boot();
}
